from typing import Literal

from pygame.event import Event

from events.event_type import EventType


class MouseMotionEvent:
    type: Literal[EventType.MOUSE_MOTION]
    """
    EventType.MOUSE_MOTION
    """

    x: int
    """
    X coordinate, relative to window
    """

    y: int
    """
    Y coordinate, relative to window
    """

    rel_x: int
    """
    The relative motion in the X direction
    """

    rel_y: int
    """
    The relative motion in the Y direction
    """

    buttons: tuple[int, int, int]
    touch: bool
    """
    Whether or not the event was generated by a touch input device
    """

    def __init__(self, event: Event):
        self.type = EventType.MOUSE_MOTION
        self.buttons = event.buttons
        [self.x, self.y] = event.pos
        [self.rel_x, self.rel_y] = event.rel
        self.touch = event.touch

    def __repr__(self):
        return f"<{self.__class__.__name__}: {self.__dict__}>"
